{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloLite",
    "version": "2.3.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-2.3.47.aar",
          "url": "NetAloLite-2.3.47.aar",
          "size": 4067801,
          "sha512": "9c4e19a652f047228802b7e167c2ef33fe75c5ad947b82ff176514a5678834aab6e7f86f355b9263ecadfc85eb2f125a72c4f3a936ce46d91fc874af8ee2c232",
          "sha256": "c02341bf46963d8a4b7628fd80544a40265ed5f7ac7a70ad43b612a089ad9e3d",
          "sha1": "d21b0df18a6617470e15c21f090f3ab75904ca9e",
          "md5": "aff8b82c97610dfbbc0d8a0b5126af26"
        }
      ]
    },
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat",
          "version": {
            "requires": "2.3.47"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.40.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-2.3.47.aar",
          "url": "NetAloLite-2.3.47.aar",
          "size": 4067801,
          "sha512": "9c4e19a652f047228802b7e167c2ef33fe75c5ad947b82ff176514a5678834aab6e7f86f355b9263ecadfc85eb2f125a72c4f3a936ce46d91fc874af8ee2c232",
          "sha256": "c02341bf46963d8a4b7628fd80544a40265ed5f7ac7a70ad43b612a089ad9e3d",
          "sha1": "d21b0df18a6617470e15c21f090f3ab75904ca9e",
          "md5": "aff8b82c97610dfbbc0d8a0b5126af26"
        }
      ]
    }
  ]
}
