{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloFull",
    "version": "3.1.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat",
          "version": {
            "requires": "3.1.33"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloLite",
          "version": {
            "requires": "3.1.33"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.github.MikeOrtiz",
          "module": "TouchImageView",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.github.fondesa",
          "module": "kpermissions",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.hbb20",
          "module": "ccp",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloFull-3.1.33.aar",
          "url": "NetAloFull-3.1.33.aar",
          "size": 10133129,
          "sha512": "d8d3f21bbc23879afdea9f4082af2fcb9a56d641aae380e9f7c30da74b7cc1fa0bfc81e6ca2f0d09b4e8ae146928cd498ea05f7c6326267b2f76db4b18729e3f",
          "sha256": "d7ea77284916bfe9f59d5b592a07569f92b0546c2e064603ba5dd05153c29cd3",
          "sha1": "022680c51b060d9f212f277129a929e6cee0ff89",
          "md5": "3557927e8c3341c283daf1d226ffbd2a"
        }
      ]
    },
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat",
          "version": {
            "requires": "3.1.33"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloLite",
          "version": {
            "requires": "3.1.33"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.github.MikeOrtiz",
          "module": "TouchImageView",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.github.fondesa",
          "module": "kpermissions",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.hbb20",
          "module": "ccp",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.42"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloFull-3.1.33.aar",
          "url": "NetAloFull-3.1.33.aar",
          "size": 10133129,
          "sha512": "d8d3f21bbc23879afdea9f4082af2fcb9a56d641aae380e9f7c30da74b7cc1fa0bfc81e6ca2f0d09b4e8ae146928cd498ea05f7c6326267b2f76db4b18729e3f",
          "sha256": "d7ea77284916bfe9f59d5b592a07569f92b0546c2e064603ba5dd05153c29cd3",
          "sha1": "022680c51b060d9f212f277129a929e6cee0ff89",
          "md5": "3557927e8c3341c283daf1d226ffbd2a"
        }
      ]
    }
  ]
}
