{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloFull-Dev",
    "version": "2.3.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "NetAloDevReleaseVariantNetAloDevReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat-Dev",
          "version": {
            "requires": "2.3.47"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloLite-Dev",
          "version": {
            "requires": "2.3.47"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.github.MikeOrtiz",
          "module": "TouchImageView",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.github.fondesa",
          "module": "kpermissions",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.hbb20",
          "module": "ccp",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloFull-Dev-2.3.47.aar",
          "url": "NetAloFull-Dev-2.3.47.aar",
          "size": 9567242,
          "sha512": "5a6f42da2f65b12414b230dc8c28b9ab3d2ebe1d780b528bd4ebd3850e9990dfb6ac56593c879c486cf2a2edbc5bd55c1b8aa926822327d7a3c8cb8dc3e3f737",
          "sha256": "4a6fa25929b11ea5ce0fed4dbfba80c2022637c1eb1d79ebf5116746c69ee077",
          "sha1": "3630acc18f2b064444b35b5039902d435c946eca",
          "md5": "3e5ef6a2160c68127d72c78a7bdba263"
        }
      ]
    },
    {
      "name": "NetAloDevReleaseVariantNetAloDevReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat-Dev",
          "version": {
            "requires": "2.3.47"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloLite-Dev",
          "version": {
            "requires": "2.3.47"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.github.MikeOrtiz",
          "module": "TouchImageView",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.github.fondesa",
          "module": "kpermissions",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.hbb20",
          "module": "ccp",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.40.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloFull-Dev-2.3.47.aar",
          "url": "NetAloFull-Dev-2.3.47.aar",
          "size": 9567242,
          "sha512": "5a6f42da2f65b12414b230dc8c28b9ab3d2ebe1d780b528bd4ebd3850e9990dfb6ac56593c879c486cf2a2edbc5bd55c1b8aa926822327d7a3c8cb8dc3e3f737",
          "sha256": "4a6fa25929b11ea5ce0fed4dbfba80c2022637c1eb1d79ebf5116746c69ee077",
          "sha1": "3630acc18f2b064444b35b5039902d435c946eca",
          "md5": "3e5ef6a2160c68127d72c78a7bdba263"
        }
      ]
    }
  ]
}
