{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloLite",
    "version": "3.1.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-3.1.30.aar",
          "url": "NetAloLite-3.1.30.aar",
          "size": 4143003,
          "sha512": "453db937e9f50d96d51ae4e7ff43e60effec16f83080c589a346cf7c6c9ca23ef2587470bdef9abfed54bbccf9e85973cad8aee4a7c4eebbb6e90657ad05f138",
          "sha256": "4cc4bdd3fa029caab90f317c4b30f2ec0bd8ba7eb9894e2de49e44ddb639abe0",
          "sha1": "3394d9250b79d0f0aebb7a7800fd36bd97ec17d3",
          "md5": "73589a98ab6910739a4a23c1ec6fe088"
        }
      ]
    },
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat",
          "version": {
            "requires": "3.1.30"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.42"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-3.1.30.aar",
          "url": "NetAloLite-3.1.30.aar",
          "size": 4143003,
          "sha512": "453db937e9f50d96d51ae4e7ff43e60effec16f83080c589a346cf7c6c9ca23ef2587470bdef9abfed54bbccf9e85973cad8aee4a7c4eebbb6e90657ad05f138",
          "sha256": "4cc4bdd3fa029caab90f317c4b30f2ec0bd8ba7eb9894e2de49e44ddb639abe0",
          "sha1": "3394d9250b79d0f0aebb7a7800fd36bd97ec17d3",
          "md5": "73589a98ab6910739a4a23c1ec6fe088"
        }
      ]
    }
  ]
}
