{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloBaseChat-Dev",
    "version": "3.1.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "NetAloDevReleaseApiElements-published",
      "attributes": {
        "brand": "NetAlo",
        "buildEnv": "dev",
        "com.android.build.api.attributes.ProductFlavor:brand": "NetAlo",
        "com.android.build.api.attributes.ProductFlavor:buildEnv": "dev",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.conscrypt",
          "module": "conscrypt-android",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.14.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.14.1"
          }
        },
        {
          "group": "jp.wasabeef.transformers",
          "module": "glide",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "jp.wasabeef.transformers",
          "module": "glide-gpu",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.jackandphantom.android",
          "module": "blurimage",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.AbedElazizShe",
          "module": "LightCompressor",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "curve25519-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "signal-protocol-android",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.abangfadli.shotwatch",
          "module": "shotwatch",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging-ktx",
          "version": {
            "requires": "23.0.6"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx",
          "version": {
            "requires": "18.2.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloBaseChat-Dev-3.1.55.aar",
          "url": "NetAloBaseChat-Dev-3.1.55.aar",
          "size": 1114372,
          "sha512": "d8d647c99f80b10b028b0e0525dd2db1f11489b7627bfe28a0e723eab5433ac204c0954b71e90841d0bd47f75c785664cfbe765a7c573bcd5a853063f677fd86",
          "sha256": "6c19121407d1100efaa7a182bd87f1bb599b0c2c68b3261f3c0667ae728c2366",
          "sha1": "c14a3344d8407491b4c93f209fc7ea7d4091ef85",
          "md5": "2419b45aef0bde610a1c85277071dbed"
        }
      ]
    },
    {
      "name": "NetAloDevReleaseRuntimeElements-published",
      "attributes": {
        "brand": "NetAlo",
        "buildEnv": "dev",
        "com.android.build.api.attributes.ProductFlavor:brand": "NetAlo",
        "com.android.build.api.attributes.ProductFlavor:buildEnv": "dev",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-tls",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.conscrypt",
          "module": "conscrypt-android",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.14.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.14.1"
          }
        },
        {
          "group": "jp.wasabeef.transformers",
          "module": "glide",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "jp.wasabeef.transformers",
          "module": "glide-gpu",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "com.jackandphantom.android",
          "module": "blurimage",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.AbedElazizShe",
          "module": "LightCompressor",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "curve25519-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "signal-protocol-android",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.abangfadli.shotwatch",
          "module": "shotwatch",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging-ktx",
          "version": {
            "requires": "23.0.6"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx",
          "version": {
            "requires": "18.2.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloBaseChat-Dev-3.1.55.aar",
          "url": "NetAloBaseChat-Dev-3.1.55.aar",
          "size": 1114372,
          "sha512": "d8d647c99f80b10b028b0e0525dd2db1f11489b7627bfe28a0e723eab5433ac204c0954b71e90841d0bd47f75c785664cfbe765a7c573bcd5a853063f677fd86",
          "sha256": "6c19121407d1100efaa7a182bd87f1bb599b0c2c68b3261f3c0667ae728c2366",
          "sha1": "c14a3344d8407491b4c93f209fc7ea7d4091ef85",
          "md5": "2419b45aef0bde610a1c85277071dbed"
        }
      ]
    }
  ]
}
