{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloLite",
    "version": "3.1.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-3.1.37.aar",
          "url": "NetAloLite-3.1.37.aar",
          "size": 4146944,
          "sha512": "9de5611278f6fa904009ef72b58a29f7be4ddfd4794aa357a87e6132678228da9a3a1d8d2bf67faa8d3bd4bfa63858302c55a397351db1f119def3e1b4053b47",
          "sha256": "858344ba8faf0144830da705b9860f420eb6d9c16e2e61d31cd5ede7feb01596",
          "sha1": "28cf49a7932a912c4e939d4238df9233e2bc815c",
          "md5": "0e499341c1372d612ca83d8b5e32fb70"
        }
      ]
    },
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat",
          "version": {
            "requires": "3.1.37"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.42"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-3.1.37.aar",
          "url": "NetAloLite-3.1.37.aar",
          "size": 4146944,
          "sha512": "9de5611278f6fa904009ef72b58a29f7be4ddfd4794aa357a87e6132678228da9a3a1d8d2bf67faa8d3bd4bfa63858302c55a397351db1f119def3e1b4053b47",
          "sha256": "858344ba8faf0144830da705b9860f420eb6d9c16e2e61d31cd5ede7feb01596",
          "sha1": "28cf49a7932a912c4e939d4238df9233e2bc815c",
          "md5": "0e499341c1372d612ca83d8b5e32fb70"
        }
      ]
    }
  ]
}
