{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloFull-Dev",
    "version": "3.1.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "NetAloDevReleaseApiElements-published",
      "attributes": {
        "brand": "NetAlo",
        "buildEnv": "dev",
        "com.android.build.api.attributes.ProductFlavor:brand": "NetAlo",
        "com.android.build.api.attributes.ProductFlavor:buildEnv": "dev",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat-Dev",
          "version": {
            "requires": "3.1.55"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloLite-Dev",
          "version": {
            "requires": "3.1.55"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.github.MikeOrtiz",
          "module": "TouchImageView",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.github.fondesa",
          "module": "kpermissions",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.hbb20",
          "module": "ccp",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloFull-Dev-3.1.55.aar",
          "url": "NetAloFull-Dev-3.1.55.aar",
          "size": 8477607,
          "sha512": "4177255b174f129a9979ea775a8841aae1b9af3a5b8e09c40f646be1dd3d44b94dde8aa0d2d935669d405457b2024d1ef70709a0a154f8a6bcdbb310b20ed9f1",
          "sha256": "31975202fd966a9a05913308a79e45401ff3550108473880f0821590cf59378e",
          "sha1": "ac9e4092295a0394bd76f51dcc60b26850e83f19",
          "md5": "befe1b47330a7114ed554cfe0166d5b3"
        }
      ]
    },
    {
      "name": "NetAloDevReleaseRuntimeElements-published",
      "attributes": {
        "brand": "NetAlo",
        "buildEnv": "dev",
        "com.android.build.api.attributes.ProductFlavor:brand": "NetAlo",
        "com.android.build.api.attributes.ProductFlavor:buildEnv": "dev",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat-Dev",
          "version": {
            "requires": "3.1.55"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloLite-Dev",
          "version": {
            "requires": "3.1.55"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.github.MikeOrtiz",
          "module": "TouchImageView",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.github.fondesa",
          "module": "kpermissions",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.hbb20",
          "module": "ccp",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.42"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloFull-Dev-3.1.55.aar",
          "url": "NetAloFull-Dev-3.1.55.aar",
          "size": 8477607,
          "sha512": "4177255b174f129a9979ea775a8841aae1b9af3a5b8e09c40f646be1dd3d44b94dde8aa0d2d935669d405457b2024d1ef70709a0a154f8a6bcdbb310b20ed9f1",
          "sha256": "31975202fd966a9a05913308a79e45401ff3550108473880f0821590cf59378e",
          "sha1": "ac9e4092295a0394bd76f51dcc60b26850e83f19",
          "md5": "befe1b47330a7114ed554cfe0166d5b3"
        }
      ]
    }
  ]
}
