{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloLite",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-2.4.1.aar",
          "url": "NetAloLite-2.4.1.aar",
          "size": 4118929,
          "sha512": "d31568d63c8538f6b3c0cc98dc540ee829409a74db287eeb9e8a5b0dcb8b109b93893cff3a47b4f6b6ab15782d8089c2a31ead43ce9b291a872d5e6333a23e98",
          "sha256": "fdf320a1ac161a7708663e02952d2904678297d2bd4b7f37ed37b85059e95bcb",
          "sha1": "953d311b45c861a306ccdee5510248705e14617a",
          "md5": "57fa514192bee91798cfd7544e193013"
        }
      ]
    },
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.11.0"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.40.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-2.4.1.aar",
          "url": "NetAloLite-2.4.1.aar",
          "size": 4118929,
          "sha512": "d31568d63c8538f6b3c0cc98dc540ee829409a74db287eeb9e8a5b0dcb8b109b93893cff3a47b4f6b6ab15782d8089c2a31ead43ce9b291a872d5e6333a23e98",
          "sha256": "fdf320a1ac161a7708663e02952d2904678297d2bd4b7f37ed37b85059e95bcb",
          "sha1": "953d311b45c861a306ccdee5510248705e14617a",
          "md5": "57fa514192bee91798cfd7544e193013"
        }
      ]
    }
  ]
}
