{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloBaseChat",
    "version": "3.1.04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "org.conscrypt",
          "module": "conscrypt-android",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "jp.wasabeef.transformers",
          "module": "glide",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.jackandphantom.android",
          "module": "blurimage",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.AbedElazizShe",
          "module": "LightCompressor",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "curve25519-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "signal-protocol-android",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.abangfadli.shotwatch",
          "module": "shotwatch",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx",
          "version": {
            "requires": "20.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging-ktx",
          "version": {
            "requires": "23.0.5"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx",
          "version": {
            "requires": "18.2.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloBaseChat-3.1.04.aar",
          "url": "NetAloBaseChat-3.1.04.aar",
          "size": 2803929,
          "sha512": "9d1ac7a16b1333c3de4904e087987df2d805a564785e5de1ff040bd04145ddd9814fe6aafb92c93dee666f2242429e593c108f4934ad2d5b6c2402cea239c551",
          "sha256": "cf8f26aecb44bafdbd3a5fe3df505c276c9844a0592937d1f27911479c8b29ba",
          "sha1": "44e271a98ea9e9ce47ae23094989af297b469646",
          "md5": "6fd05393b8a61e95cb95fbfa494c6c13"
        }
      ]
    },
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "org.conscrypt",
          "module": "conscrypt-android",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.13.0"
          }
        },
        {
          "group": "jp.wasabeef.transformers",
          "module": "glide",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.jackandphantom.android",
          "module": "blurimage",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.AbedElazizShe",
          "module": "LightCompressor",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "curve25519-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.whispersystems",
          "module": "signal-protocol-android",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.abangfadli.shotwatch",
          "module": "shotwatch",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx",
          "version": {
            "requires": "20.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging-ktx",
          "version": {
            "requires": "23.0.5"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx",
          "version": {
            "requires": "18.2.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloBaseChat-3.1.04.aar",
          "url": "NetAloBaseChat-3.1.04.aar",
          "size": 2803929,
          "sha512": "9d1ac7a16b1333c3de4904e087987df2d805a564785e5de1ff040bd04145ddd9814fe6aafb92c93dee666f2242429e593c108f4934ad2d5b6c2402cea239c551",
          "sha256": "cf8f26aecb44bafdbd3a5fe3df505c276c9844a0592937d1f27911479c8b29ba",
          "sha1": "44e271a98ea9e9ce47ae23094989af297b469646",
          "md5": "6fd05393b8a61e95cb95fbfa494c6c13"
        }
      ]
    }
  ]
}
