{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloLite-Dev",
    "version": "2.3.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "NetAloDevReleaseVariantNetAloDevReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-Dev-2.3.44.aar",
          "url": "NetAloLite-Dev-2.3.44.aar",
          "size": 4068657,
          "sha512": "226f0101c7c53e4dfe10dda7d52049eede7f72aa264200ccde7cc745bbc2d5350ff9f32c6922e8aba71d637593ed8cd23786a145516fe165cf7e110c9aa7449a",
          "sha256": "02d5e7490ecb78ccf7be9860771661333f09dd7210db9b2bf9b8443e7b54b50a",
          "sha1": "49ea73a864befe40fee58f8e8de3f4b9bcf15f1e",
          "md5": "e5db94e97c59b0b59916f8443bd20210"
        }
      ]
    },
    {
      "name": "NetAloDevReleaseVariantNetAloDevReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.10.1"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat-Dev",
          "version": {
            "requires": "2.3.44"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.40.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-Dev-2.3.44.aar",
          "url": "NetAloLite-Dev-2.3.44.aar",
          "size": 4068657,
          "sha512": "226f0101c7c53e4dfe10dda7d52049eede7f72aa264200ccde7cc745bbc2d5350ff9f32c6922e8aba71d637593ed8cd23786a145516fe165cf7e110c9aa7449a",
          "sha256": "02d5e7490ecb78ccf7be9860771661333f09dd7210db9b2bf9b8443e7b54b50a",
          "sha1": "49ea73a864befe40fee58f8e8de3f4b9bcf15f1e",
          "md5": "e5db94e97c59b0b59916f8443bd20210"
        }
      ]
    }
  ]
}
