{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloLite",
    "version": "3.1.55",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "NetAloProdReleaseApiElements-published",
      "attributes": {
        "brand": "NetAlo",
        "buildEnv": "prod",
        "com.android.build.api.attributes.ProductFlavor:brand": "NetAlo",
        "com.android.build.api.attributes.ProductFlavor:buildEnv": "prod",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.13.1-transformer-api"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.13.1-transformer-api"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.13.1-transformer-api"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-3.1.55.aar",
          "url": "NetAloLite-3.1.55.aar",
          "size": 1880343,
          "sha512": "11be3000f204cf1b18b3a6137196505c9c75a7108722359d36721228d1bda0a26041b416505a5ac97a3694c781a72ad1925c808ec03a5bff43c5d27223215c9e",
          "sha256": "c4b4f4e4d8643fb110ef346a81bb9c31ef4c258dd437b79b5463466e0416b6c3",
          "sha1": "d3755d3b80f2991feca7c6f3b77a903eebd7d090",
          "md5": "1e50dcba487e72f3e4c9ee2bc5188d19"
        }
      ]
    },
    {
      "name": "NetAloProdReleaseRuntimeElements-published",
      "attributes": {
        "brand": "NetAlo",
        "buildEnv": "prod",
        "com.android.build.api.attributes.ProductFlavor:brand": "NetAlo",
        "com.android.build.api.attributes.ProductFlavor:buildEnv": "prod",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.13.1-transformer-api"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.13.1-transformer-api"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.13.1-transformer-api"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat",
          "version": {
            "requires": "3.1.55"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.42"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloLite-3.1.55.aar",
          "url": "NetAloLite-3.1.55.aar",
          "size": 1880343,
          "sha512": "11be3000f204cf1b18b3a6137196505c9c75a7108722359d36721228d1bda0a26041b416505a5ac97a3694c781a72ad1925c808ec03a5bff43c5d27223215c9e",
          "sha256": "c4b4f4e4d8643fb110ef346a81bb9c31ef4c258dd437b79b5463466e0416b6c3",
          "sha1": "d3755d3b80f2991feca7c6f3b77a903eebd7d090",
          "md5": "1e50dcba487e72f3e4c9ee2bc5188d19"
        }
      ]
    }
  ]
}
