{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.netacom",
    "module": "NetAloFull",
    "version": "3.1.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat",
          "version": {
            "requires": "3.1.40"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloLite",
          "version": {
            "requires": "3.1.40"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.github.MikeOrtiz",
          "module": "TouchImageView",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.github.fondesa",
          "module": "kpermissions",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.hbb20",
          "module": "ccp",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloFull-3.1.40.aar",
          "url": "NetAloFull-3.1.40.aar",
          "size": 10197726,
          "sha512": "0633c2e9c7c6a0672f44b5dcedc4040a7fbc618dc25d737c10ec5c719c2151b07069e09e0924fa21dcac1a475c7bf43ede53b73d489d7434f9b6127273282a7f",
          "sha256": "05d2e24339d193ae6625b27a126fcb2ae4c7d924d16ef12600238ee3e4e7e36e",
          "sha1": "daa17801a0b0a9cb3cd1a7c5ce1399a3dca0351d",
          "md5": "c3c996828988b998a41e81ccc3bf3706"
        }
      ]
    },
    {
      "name": "NetAloProdReleaseVariantNetAloProdReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloBaseChat",
          "version": {
            "requires": "3.1.40"
          }
        },
        {
          "group": "vn.netacom",
          "module": "NetAloLite",
          "version": {
            "requires": "3.1.40"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.github.MikeOrtiz",
          "module": "TouchImageView",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.github.fondesa",
          "module": "kpermissions",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.hbb20",
          "module": "ccp",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.42"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.michaelrocks",
          "module": "libphonenumber-android",
          "version": {
            "requires": "8.12.22"
          }
        }
      ],
      "files": [
        {
          "name": "NetAloFull-3.1.40.aar",
          "url": "NetAloFull-3.1.40.aar",
          "size": 10197726,
          "sha512": "0633c2e9c7c6a0672f44b5dcedc4040a7fbc618dc25d737c10ec5c719c2151b07069e09e0924fa21dcac1a475c7bf43ede53b73d489d7434f9b6127273282a7f",
          "sha256": "05d2e24339d193ae6625b27a126fcb2ae4c7d924d16ef12600238ee3e4e7e36e",
          "sha1": "daa17801a0b0a9cb3cd1a7c5ce1399a3dca0351d",
          "md5": "c3c996828988b998a41e81ccc3bf3706"
        }
      ]
    }
  ]
}
